# This compose file is intended for local development only.
services:
  postgres_bot:
    extends:
      file: controlpanel/docker-compose.yml
      service: postgres_bot
    env_file:
      - .env
    volumes:
      - ./controlpanel/data/postgres/:/var/lib/postgresql/data
  
  # Depeneds on breaks the build
  # bot_control_panel:
  #   extends:
  #     file: controlpanel/docker-compose.yml
  #     service: bot_control_panel

  #   networks:
  #     - ds_net

  # So here is the workaround

  bot_control_panel:
    extends:
      file: controlpanel/docker-compose.yml
      service: bot_control_panel
    env_file:
      - .env
    volumes:
      - ./controlpanel/migrations:/controlpanel/migrations
    command: "--development"
    develop:
      watch:
        - action: sync
          path: ./controlpanel/web/
          target: /controlpanel/web/
          ignore: 
            - "**/__pycache__/"   

        - action: rebuild
          path: ./controlpanel/Dockerfile

        - action: sync+restart 
          path: ./controlpanel/scripts/entrypoint.sh
          target: /controlpanel/entrypoint.sh

        - action: rebuild
          path: ./controlpanel/requirements.txt

  discord_bot:
    extends:
      file: bot/docker-compose.yml
      service: discord_bot
    command: "python bot.py"
    develop:
      watch:
        - action: sync+restart
          path: ./bot/src/
          target: /discord_bot/src/
          ignore: 
            - __pycache__/

networks:
  ds_net:
    driver: bridge