version: '3.7'

services:
  discord_bot:
    build: .
    restart: unless-stopped
    container_name: discord_bot
    env_file:
      - .env
    volumes:
      - ./bot/data:/discord_bot/data
      - ./bot/assets/:/discord_bot/assets/