"""first migration

Revision ID: 44934ee10952
Revises: 
Create Date: 2024-01-04 22:18:02.612667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44934ee10952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'USER', name='roleenum'), nullable=True),
    sa.Column('use_discord_username', sa.Boolean(), nullable=True),
    sa.Column('username_matches_discord', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('silksong_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silksong_news')
    op.drop_table('users')
    # ### end Alembic commands ###
