"""expand message limit

Revision ID: 6dddf5a823da
Revises: a412ed9a05b2
Create Date: 2024-02-03 14:21:31.755960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dddf5a823da'
down_revision = 'a412ed9a05b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silksong_news', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=1750),
               type_=sa.String(length=1800),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silksong_news', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.String(length=1800),
               type_=sa.VARCHAR(length=1750),
               existing_nullable=False)

    # ### end Alembic commands ###
