"""init

Revision ID: b5159f13e38b
Revises: 
Create Date: 2024-01-20 13:40:05.032038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5159f13e38b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'USER', name='roleenum'), nullable=False),
    sa.Column('use_discord_username', sa.Boolean(), nullable=False),
    sa.Column('username_matches_discord', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('silksong_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1750), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silksong_news')
    op.drop_table('users')
    # ### end Alembic commands ###
