version: '3.7'

services:
  bot_control_panel:
    build: .
    restart: unless-stopped
    container_name: bot_control_panel
    environment:
      - TZ=${TZ}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_APP=${FLASK_APP:-web}
    depends_on:
      - postgres_bot
    ports:
      - 8000:8000
    networks:
      - ds_net
  
  postgres_bot:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres_bot
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/discordbot/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ds_net

  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/discordbot/data/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - ds_net
    depends_on:
      - bot_control_panel

networks:
  ds_net:
    external: true
