version: '3.7'

services:
  bot_control_panel:
    build: .
    restart: unless-stopped
    container_name: bot_control_panel
    environment:
      - TZ=${TZ}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_APP=${FLASK_APP:-web}
      - PREFERRED_URL_SCHEME=${PREFERRED_URL_SCHEME:-https}
      - CONTROL_PANEL_ADMIN_ID=${CONTROL_PANEL_ADMIN_ID}
    depends_on:
      - postgres_bot
    networks:
      - ds_net
  
  postgres_bot:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres_bot
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/discordbot/data/postgres:/var/lib/postgresql/data
    networks:
      - ds_net

  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
      - /etc/letsencrypt/live/diablostrike.com/:/etc/letsencrypt/live/diablostrike.com/:ro
      - /etc/letsencrypt/archive/diablostrike.com/:/etc/letsencrypt/archive/diablostrike.com/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - ds_net
    depends_on:
      - bot_control_panel

networks:
  ds_net:
    external: true
